<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Cart__CLASSMETADATA__' => 0,
'App__Entity__Category__CLASSMETADATA__' => 1,
'App__Entity__Order__CLASSMETADATA__' => 2,
'App__Entity__OrderProduct__CLASSMETADATA__' => 3,
'App__Entity__Product__CLASSMETADATA__' => 4,
'App__Entity__User__CLASSMETADATA__' => 5,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Cart',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\CartRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'product_title' => $o[2],
                        'price' => $o[3],
                        'quantity' => $o[4],
                        'image' => $o[5],
                        'created_at' => $o[6],
                        'updated_at' => $o[7],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'product_title' => 'product_title',
                        'price' => 'price',
                        'quantity' => 'quantity',
                        'image' => 'image',
                        'created_at' => 'created_at',
                        'updated_at' => 'updated_at',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'product_title' => 'product_title',
                        'price' => 'price',
                        'quantity' => 'quantity',
                        'image' => 'image',
                        'created_at' => 'created_at',
                        'updated_at' => 'updated_at',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'cart',
                    ],
                ],
                'associationMappings' => [
                    [
                        'product' => $o[8],
                        'user' => $o[10],
                    ],
                ],
                'idGenerator' => [
                    $o[12],
                ],
                'name' => [
                    'App\\Entity\\Cart',
                    9 => 'product_id',
                    11 => 'user_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'decimal',
                    'integer',
                    'string',
                    'datetime_immutable',
                    'datetime_immutable',
                ],
                'fieldName' => [
                    1 => 'id',
                    'product_title',
                    'price',
                    'quantity',
                    'image',
                    'created_at',
                    'updated_at',
                ],
                'columnName' => [
                    1 => 'id',
                    'product_title',
                    'price',
                    'quantity',
                    'image',
                    'created_at',
                    'updated_at',
                ],
                'length' => [
                    2 => 255,
                    5 => 255,
                ],
                'nullable' => [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                'precision' => [
                    3 => 10,
                ],
                'scale' => [
                    3 => 2,
                ],
                'fetch' => [
                    8 => 2,
                    10 => 2,
                ],
                'sourceEntity' => [
                    8 => 'App\\Entity\\Cart',
                    10 => 'App\\Entity\\Cart',
                ],
                'sourceToTargetKeyColumns' => [
                    8 => [
                        'product_id' => 'id',
                    ],
                    10 => [
                        'user_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    8 => [
                        'id' => 'product_id',
                    ],
                    10 => [
                        'id' => 'user_id',
                    ],
                ],
                'joinColumns' => [
                    8 => [
                        $o[9],
                    ],
                    10 => [
                        $o[11],
                    ],
                ],
                'joinColumnFieldNames' => [
                    8 => [
                        'product_id' => 'product_id',
                    ],
                    10 => [
                        'user_id' => 'user_id',
                    ],
                ],
                'referencedColumnName' => [
                    9 => 'id',
                    11 => 'id',
                ],
                'inversedBy' => [
                    10 => 'cart',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    8 => 'product',
                    10 => 'user',
                ],
                'targetEntity' => [
                    8 => 'App\\Entity\\Product',
                    10 => 'App\\Entity\\User',
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Category',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\CategoryRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'name' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'category',
                    ],
                ],
                'associationMappings' => [
                    [
                        'products' => $o[3],
                    ],
                ],
                'idGenerator' => [
                    $o[4],
                ],
                'name' => [
                    'App\\Entity\\Category',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'name',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                ],
                'length' => [
                    2 => 255,
                ],
                'fetch' => [
                    3 => 2,
                ],
                'sourceEntity' => [
                    3 => 'App\\Entity\\Category',
                ],
                'mappedBy' => [
                    3 => 'category',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    3 => 'products',
                ],
                'targetEntity' => [
                    3 => 'App\\Entity\\Product',
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Order',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\OrderRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'name' => $o[2],
                        'email' => $o[3],
                        'phone' => $o[4],
                        'address' => $o[5],
                        'city' => $o[6],
                        'payment_method' => $o[7],
                        'payment_status' => $o[8],
                        'transaction_id' => $o[9],
                        'total' => $o[10],
                        'created_at' => $o[11],
                        'updated_at' => $o[12],
                        'paid_amount' => $o[13],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                        'email' => 'email',
                        'phone' => 'phone',
                        'address' => 'address',
                        'city' => 'city',
                        'payment_method' => 'payment_method',
                        'payment_status' => 'payment_status',
                        'transaction_id' => 'transaction_id',
                        'total' => 'total',
                        'created_at' => 'created_at',
                        'updated_at' => 'updated_at',
                        'paid_amount' => 'paid_amount',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                        'email' => 'email',
                        'phone' => 'phone',
                        'address' => 'address',
                        'city' => 'city',
                        'payment_method' => 'payment_method',
                        'payment_status' => 'payment_status',
                        'transaction_id' => 'transaction_id',
                        'total' => 'total',
                        'created_at' => 'created_at',
                        'updated_at' => 'updated_at',
                        'paid_amount' => 'paid_amount',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'order',
                        'quoted' => true,
                    ],
                ],
                'associationMappings' => [
                    [
                        'orderProducts' => $o[14],
                        'user' => $o[15],
                    ],
                ],
                'idGenerator' => [
                    $o[17],
                ],
                'name' => [
                    'App\\Entity\\Order',
                    16 => 'user_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'decimal',
                    'datetime_immutable',
                    'datetime_immutable',
                    'decimal',
                ],
                'fieldName' => [
                    1 => 'id',
                    'name',
                    'email',
                    'phone',
                    'address',
                    'city',
                    'payment_method',
                    'payment_status',
                    'transaction_id',
                    'total',
                    'created_at',
                    'updated_at',
                    'paid_amount',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'email',
                    'phone',
                    'address',
                    'city',
                    'payment_method',
                    'payment_status',
                    'transaction_id',
                    'total',
                    'created_at',
                    'updated_at',
                    'paid_amount',
                ],
                'length' => [
                    2 => 255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                ],
                'nullable' => [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                'precision' => [
                    10 => 10,
                    13 => 10,
                ],
                'scale' => [
                    10 => 2,
                    13 => 2,
                ],
                'fetch' => [
                    14 => 2,
                    2,
                ],
                'sourceEntity' => [
                    14 => 'App\\Entity\\Order',
                    'App\\Entity\\Order',
                ],
                'mappedBy' => [
                    14 => 'order',
                ],
                'inversedBy' => [
                    15 => 'orders',
                ],
                'sourceToTargetKeyColumns' => [
                    15 => [
                        'user_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    15 => [
                        'id' => 'user_id',
                    ],
                ],
                'joinColumns' => [
                    15 => [
                        $o[16],
                    ],
                ],
                'joinColumnFieldNames' => [
                    15 => [
                        'user_id' => 'user_id',
                    ],
                ],
                'referencedColumnName' => [
                    16 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    14 => 'orderProducts',
                    'user',
                ],
                'targetEntity' => [
                    14 => 'App\\Entity\\OrderProduct',
                    'App\\Entity\\User',
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\OrderProduct',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\OrderProductRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'title' => $o[2],
                        'quantity' => $o[3],
                        'price' => $o[4],
                        'created_at' => $o[5],
                        'updated_at' => $o[6],
                        'status' => $o[7],
                        'image' => $o[8],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'title' => 'title',
                        'quantity' => 'quantity',
                        'price' => 'price',
                        'created_at' => 'created_at',
                        'updated_at' => 'updated_at',
                        'status' => 'status',
                        'image' => 'image',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'title' => 'title',
                        'quantity' => 'quantity',
                        'price' => 'price',
                        'created_at' => 'created_at',
                        'updated_at' => 'updated_at',
                        'status' => 'status',
                        'image' => 'image',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'order_product',
                    ],
                ],
                'associationMappings' => [
                    [
                        'order' => $o[9],
                        'product' => $o[11],
                        'user' => $o[13],
                    ],
                ],
                'idGenerator' => [
                    $o[15],
                ],
                'name' => [
                    'App\\Entity\\OrderProduct',
                    10 => 'order_id',
                    12 => 'product_id',
                    14 => 'user_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'integer',
                    'decimal',
                    'datetime_immutable',
                    'datetime_immutable',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'title',
                    'quantity',
                    'price',
                    'created_at',
                    'updated_at',
                    'status',
                    'image',
                ],
                'columnName' => [
                    1 => 'id',
                    'title',
                    'quantity',
                    'price',
                    'created_at',
                    'updated_at',
                    'status',
                    'image',
                ],
                'length' => [
                    2 => 255,
                    7 => 20,
                    255,
                ],
                'nullable' => [
                    2 => true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                ],
                'precision' => [
                    4 => 10,
                ],
                'scale' => [
                    4 => 2,
                ],
                'fetch' => [
                    9 => 2,
                    11 => 2,
                    13 => 2,
                ],
                'sourceEntity' => [
                    9 => 'App\\Entity\\OrderProduct',
                    11 => 'App\\Entity\\OrderProduct',
                    13 => 'App\\Entity\\OrderProduct',
                ],
                'inversedBy' => [
                    9 => 'orderProducts',
                    11 => 'orderProducts',
                    13 => 'orderProducts',
                ],
                'sourceToTargetKeyColumns' => [
                    9 => [
                        'order_id' => 'id',
                    ],
                    11 => [
                        'product_id' => 'id',
                    ],
                    13 => [
                        'user_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    9 => [
                        'id' => 'order_id',
                    ],
                    11 => [
                        'id' => 'product_id',
                    ],
                    13 => [
                        'id' => 'user_id',
                    ],
                ],
                'joinColumns' => [
                    9 => [
                        $o[10],
                    ],
                    11 => [
                        $o[12],
                    ],
                    13 => [
                        $o[14],
                    ],
                ],
                'joinColumnFieldNames' => [
                    9 => [
                        'order_id' => 'order_id',
                    ],
                    11 => [
                        'product_id' => 'product_id',
                    ],
                    13 => [
                        'user_id' => 'user_id',
                    ],
                ],
                'referencedColumnName' => [
                    10 => 'id',
                    12 => 'id',
                    14 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    9 => 'order',
                    11 => 'product',
                    13 => 'user',
                ],
                'targetEntity' => [
                    9 => 'App\\Entity\\Order',
                    11 => 'App\\Entity\\Product',
                    13 => 'App\\Entity\\User',
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Product',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ProductRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'title' => $o[2],
                        'description' => $o[3],
                        'short_notes' => $o[4],
                        'price' => $o[5],
                        'image' => $o[6],
                        'user_id' => $o[7],
                        'created_at' => $o[8],
                        'updated_at' => $o[9],
                        'discount_price' => $o[10],
                        'quantity' => $o[11],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'title' => 'title',
                        'description' => 'description',
                        'short_notes' => 'short_notes',
                        'price' => 'price',
                        'image' => 'image',
                        'user_id' => 'user_id',
                        'created_at' => 'created_at',
                        'updated_at' => 'updated_at',
                        'discount_price' => 'discount_price',
                        'quantity' => 'quantity',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'title' => 'title',
                        'description' => 'description',
                        'short_notes' => 'short_notes',
                        'price' => 'price',
                        'image' => 'image',
                        'user_id' => 'user_id',
                        'created_at' => 'created_at',
                        'updated_at' => 'updated_at',
                        'discount_price' => 'discount_price',
                        'quantity' => 'quantity',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'product',
                    ],
                ],
                'associationMappings' => [
                    [
                        'category' => $o[12],
                        'orderProducts' => $o[14],
                    ],
                ],
                'idGenerator' => [
                    $o[15],
                ],
                'name' => [
                    'App\\Entity\\Product',
                    13 => 'category_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'text',
                    'string',
                    'decimal',
                    'string',
                    'bigint',
                    'datetime_immutable',
                    'datetime_immutable',
                    'decimal',
                    'integer',
                ],
                'fieldName' => [
                    1 => 'id',
                    'title',
                    'description',
                    'short_notes',
                    'price',
                    'image',
                    'user_id',
                    'created_at',
                    'updated_at',
                    'discount_price',
                    'quantity',
                ],
                'columnName' => [
                    1 => 'id',
                    'title',
                    'description',
                    'short_notes',
                    'price',
                    'image',
                    'user_id',
                    'created_at',
                    'updated_at',
                    'discount_price',
                    'quantity',
                ],
                'length' => [
                    2 => 255,
                    4 => 255,
                    6 => 255,
                ],
                'precision' => [
                    5 => 10,
                    10 => 10,
                ],
                'scale' => [
                    5 => 2,
                    10 => 2,
                ],
                'nullable' => [
                    6 => true,
                    8 => true,
                    true,
                    true,
                    true,
                ],
                'fetch' => [
                    12 => 2,
                    14 => 2,
                ],
                'sourceEntity' => [
                    12 => 'App\\Entity\\Product',
                    14 => 'App\\Entity\\Product',
                ],
                'inversedBy' => [
                    12 => 'products',
                ],
                'sourceToTargetKeyColumns' => [
                    12 => [
                        'category_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    12 => [
                        'id' => 'category_id',
                    ],
                ],
                'joinColumns' => [
                    12 => [
                        $o[13],
                    ],
                ],
                'joinColumnFieldNames' => [
                    12 => [
                        'category_id' => 'category_id',
                    ],
                ],
                'referencedColumnName' => [
                    13 => 'id',
                ],
                'mappedBy' => [
                    14 => 'product',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    12 => 'category',
                    14 => 'orderProducts',
                ],
                'targetEntity' => [
                    12 => 'App\\Entity\\Category',
                    14 => 'App\\Entity\\OrderProduct',
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'email' => $o[2],
                        'roles' => $o[3],
                        'password' => $o[4],
                        'email_verifiet_at' => $o[5],
                        'name' => $o[6],
                        'remember_token' => $o[7],
                        'created_at' => $o[8],
                        'updated_at' => $o[9],
                        'isVerified' => $o[10],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'roles' => 'roles',
                        'password' => 'password',
                        'email_verifiet_at' => 'email_verifiet_at',
                        'name' => 'name',
                        'remember_token' => 'remember_token',
                        'created_at' => 'created_at',
                        'updated_at' => 'updated_at',
                        'is_verified' => 'isVerified',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'roles' => 'roles',
                        'password' => 'password',
                        'email_verifiet_at' => 'email_verifiet_at',
                        'name' => 'name',
                        'remember_token' => 'remember_token',
                        'created_at' => 'created_at',
                        'updated_at' => 'updated_at',
                        'isVerified' => 'is_verified',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                        'uniqueConstraints' => [
                            'UNIQ_IDENTIFIER_EMAIL' => [
                                'fields' => [
                                    'email',
                                ],
                            ],
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'cart' => $o[11],
                        'orderProducts' => $o[12],
                        'orders' => $o[13],
                    ],
                ],
                'idGenerator' => [
                    $o[14],
                ],
                'name' => [
                    'App\\Entity\\User',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'json',
                    'string',
                    'datetime_immutable',
                    'string',
                    'string',
                    'datetime_immutable',
                    'datetime_immutable',
                    'boolean',
                ],
                'fieldName' => [
                    1 => 'id',
                    'email',
                    'roles',
                    'password',
                    'email_verifiet_at',
                    'name',
                    'remember_token',
                    'created_at',
                    'updated_at',
                    'isVerified',
                ],
                'columnName' => [
                    1 => 'id',
                    'email',
                    'roles',
                    'password',
                    'email_verifiet_at',
                    'name',
                    'remember_token',
                    'created_at',
                    'updated_at',
                    'is_verified',
                ],
                'length' => [
                    2 => 180,
                    6 => 255,
                    100,
                ],
                'nullable' => [
                    5 => true,
                    7 => true,
                    true,
                    true,
                ],
                'fetch' => [
                    11 => 2,
                    2,
                    2,
                ],
                'sourceEntity' => [
                    11 => 'App\\Entity\\User',
                    'App\\Entity\\User',
                    'App\\Entity\\User',
                ],
                'mappedBy' => [
                    11 => 'user',
                    'user',
                    'user',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    11 => 'cart',
                    'orderProducts',
                    'orders',
                ],
                'targetEntity' => [
                    11 => 'App\\Entity\\Cart',
                    'App\\Entity\\OrderProduct',
                    'App\\Entity\\Order',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
