<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBxayfxv\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBxayfxv/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBxayfxv.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBxayfxv\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerBxayfxv\App_KernelProdContainer([
    'container.build_hash' => 'Bxayfxv',
    'container.build_id' => 'dc6d54ed',
    'container.build_time' => 1715345918,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBxayfxv');
