<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \App\Entity\Order implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'orderProducts' => [parent::class, 'orderProducts', null],
        "\0".parent::class."\0".'paid_amount' => [parent::class, 'paid_amount', null],
        "\0".parent::class."\0".'payment_method' => [parent::class, 'payment_method', null],
        "\0".parent::class."\0".'payment_status' => [parent::class, 'payment_status', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'total' => [parent::class, 'total', null],
        "\0".parent::class."\0".'transaction_id' => [parent::class, 'transaction_id', null],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'address' => [parent::class, 'address', null],
        'city' => [parent::class, 'city', null],
        'created_at' => [parent::class, 'created_at', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'orderProducts' => [parent::class, 'orderProducts', null],
        'paid_amount' => [parent::class, 'paid_amount', null],
        'payment_method' => [parent::class, 'payment_method', null],
        'payment_status' => [parent::class, 'payment_status', null],
        'phone' => [parent::class, 'phone', null],
        'total' => [parent::class, 'total', null],
        'transaction_id' => [parent::class, 'transaction_id', null],
        'updated_at' => [parent::class, 'updated_at', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
