<?php

namespace ContainerBxayfxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PgyqJ7IService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.PgyqJ7I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PgyqJ7I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'oprep' => ['privates', 'App\\Repository\\OrderProductRepository', 'getOrderProductRepositoryService', true],
        ], [
            'oprep' => 'App\\Repository\\OrderProductRepository',
        ]);
    }
}
