<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cart extends \App\Entity\Cart implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null],
        "\0".parent::class."\0".'product' => [parent::class, 'product', null],
        "\0".parent::class."\0".'product_title' => [parent::class, 'product_title', null],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'created_at' => [parent::class, 'created_at', null],
        'id' => [parent::class, 'id', null],
        'image' => [parent::class, 'image', null],
        'price' => [parent::class, 'price', null],
        'product' => [parent::class, 'product', null],
        'product_title' => [parent::class, 'product_title', null],
        'quantity' => [parent::class, 'quantity', null],
        'updated_at' => [parent::class, 'updated_at', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
